server {
    listen 80;
    server_name ~^(?<project>.+)\.devploy\.run\.place$;

    root /opt/render/project/src/backend/projects/$project;

    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
